---
- name: Deploy Prometheus on IBM Cloud Kubernetes Service (IKS)
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Set up Prometheus configuration
      k8s:
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: prometheus-config
            namespace: prometheus
          data:
            prometheus.yml: |
              global:
                scrape_interval: 15s

              scrape_configs:
                - job_name: 'node'
                  static_configs:
                    - targets: ['localhost:9100']

    - name: Deploy Prometheus
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: prometheus-service
            namespace: prometheus
          spec:
            selector:
              app: prometheus
            ports:
              - name: web
                port: 9090
                targetPort: 9090
        wait: yes

    - name: Expose Prometheus service
      k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: prometheus-ingress
            namespace: prometheus
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            rules:
              - host: prometheus.example.com
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: prometheus-service
                          port:
                            number: 9090
        wait: yes
